### PR TITLE
fix: handle CSV votes proposals with shutter

### LINKED ISSUE #256: bug: invalid votes reports when vote is not valid (when using shutter)
Test by downloadin CSV from https://snapshot-git-fix-allow-boost-on-shutter-proposal-snapshot.vercel.app/#/thanku.eth/proposal/0x0da0673d17298e8f52c88385959952d21c2d0ae2fff2f0fea9df02ca0590cb6a

CSV content looks like

```csv
address,choice.1,choice.2,choice.3,choice.4,voting_power,timestamp,author_ipfs_hash,reason
0x24F15402C6Bb870554489b2fd2049A85d75B982f,1,2,3,4,1,1712916940,bafkreidjaajithd6eyoxlnxhth22bqu44wlq3eh3qajdwrtluqeqkrj4bi,""
0x89446aF03652c5257dB5C8E4E85495EB754196c5,x,2,4,2,a,3,e,d,d,3,4,0,a,a,e,a,6,f,4,b,9,b,7,8,5,3,5,f,2,d,7,3,c,0,5,4,2,4,2,2,4,a,8,e,1,a,8,b,7,9,6,a,4,8,b,b,6,3,b,4,d,1,2,e,4,2,3,0,d,b,0,4,e,8,d,e,c,3,7,2,2,4,7,c,5,e,0,b,7,4,7,1,5,8,8,a,3,6,3,f,3,7,9,7,a,6,e,5,3,b,6,6,1,5,5,3,6,3,1,3,9,a,c,4,4,6,b,0,6,0,0,0,6,f,5,e,2,0,a,3,0,8,0,9,5,f,6,9,c,0,8,8,5,8,c,c,8,0,d,6,6,3,2,5,b,2,7,d,5,0,a,8,7,b,8,a,3,9,9,e,6,5,8,6,b,d,f,4,7,0,7,8,c,1,1,2,1,8,8,3,6,1,f,b,b,7,8,6,2,1,c,9,b,3,2,6,3,2,2,d,3,6,d,5,d,a,1,4,c,8,b,2,a,1,a,a,3,e,a,0,3,a,c,1,c,e,4,c,7,b,3,d,2,9,7,a,b,a,2,6,d,2,2,0,c,a,c,9,8,e,e,c,3,3,4,c,c,e,e,0,d,4,2,9,f,2,7,9,e,0,a,0,b,f,c,7,0,c,a,1,5,0,5,2,5,0,1,1,4,5,1,f,f,3,0,e,1,f,8,7,f,2,c,e,8,4,4,e,2,1,d,b,8,a,e,0,8,3,7,2,c,c,1,6,4,c,9,3,5,6,a,5,0,4,d,9,f,3,7,a,4,3,7,f,d,d,5,4,9,a,1,a,7,f,4,d,1,a,b,5,7,3,2,3,6,a,a,a,a,a,1,1712917391,bafkreida3kmg7vznhcqiqafvuxowk3j7ttvavv7s5nd4zzgl26b6tsn3cu,""
```

### PR DESCRIPTION
**Pull request by wa0x6e**
## 🧿 Current issues / What's wrong ?

Closes #256

Current votes report looks at the type of the returned choices object (number, number[], or {}), to decide how to format them on the CSV file.

This fail on proposals with shutter, which return a string when not closed yet, and still a string when the choice is invalid (edge case)

## 💊 Fixes / Solution

- Stop inferring the choices format from the choices object, and look at the proposal type instead (single, approval, weighted, etc ...)
- Do not return any choices for active shutter proposals
- Return empty choices for invalid shutter choices

## 🛠️ Tests

- Run `yarn test`
- Test should pass (ignore the failing test due to NFT claimer, see https://github.com/snapshot-labs/snapshot-sidekick/pull/259)
- `curl -X POST localhost:3005/api/votes/0x0da0673d17298e8f52c88385959952d21c2d0ae2fff2f0fea9df02ca0590cb6a`
- The CSV file should contain all the votes, with the one with invalid choice shown as no choices

### CODE REVIEW

File: src/lib/votesReport.ts [hunk 1]
```diff
@@ -43,9 +43,9 @@ class VotesReport extends Cache {
 
     const headers = [
       'address',
-      votes.length === 0 || typeof votes[0].choice === 'number'
+      ['basic', 'single-choice'].includes(this.proposal!.type)
         ? 'choice'
-        : this.proposal && this.proposal.choices.map((_choice, index) => `choice.${index + 1}`),
+        : this.proposal!.choices.map((_choice, index) => `choice.${index + 1}`),
```
Comment (ChaituVR) [inline src/lib/votesReport.ts:48]: Could we add a condition on top level to ignore everything if there is no proposal. else we have to check it everywhere

Comment (wa0x6e) [reply src/lib/votesReport.ts:48]: the `!` is just for typescript, as this function is never called if proposal is missing, thanks to the check on line 19

**Review by ChaituVR — APPROVED** [review]
tAck
